let v1= prompt("Digite um numero");
let v2= prompt("Digite um numero");
let v3= prompt("Digite um numero");
let v4= prompt("Digite um numero");
v1 = Number(v1);
v2 = Number(v2);
v3 = Number(v3);
v4 = Number(v4);
let s=v2+v4;
let m=v1*v3;
document.write(`${v2}+${v4}=${s}`);
document.write("<br>");
document.write(`${v1}*${v3}=${m}`);